"""create orders table

Revision ID: 15280868bca9
Revises: 831d972d9ff7
Create Date: 2026-10-05 17:43:37.537073

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '15280868bca9'
down_revision: Union[str, Sequence[str], None] = '831d972d9ff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'orders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column(
            'status',
            sa.Enum(
                'new',
                'paid',
                'cancelled',
                'in_transit',
                'completed',
                name='order_status',
            ),
            server_default='new',
            nullable=False,
        ),
        sa.Column('user_name', sa.String(length=128), nullable=False),
        sa.Column('user_phone_number', sa.String(length=16), nullable=False),
        sa.Column('user_email', sa.String(length=254), nullable=True),
        sa.Column('user_city', sa.String(length=255), nullable=False),
        sa.Column('user_address', sa.String(length=500), nullable=False),
        sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders', if_exists=True)
    sa.Enum(name='order_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
