"""create payments table

Revision ID: 1fda7e15320d
Revises: 9b624e0f13ad
Create Date: 2026-10-09 12:00:44.901400

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1fda7e15320d'
down_revision: Union[str, Sequence[str], None] = '9b624e0f13ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'payments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=False),
        sa.Column('provider', sa.String(length=128), nullable=False),
        sa.Column('provider_payment_id', sa.String(length=256), nullable=True),
        sa.Column(
            'status',
            sa.Enum(
                'pending', 'succeeded', 'failed', 'cancelled', name='payment_status'
            ),
            server_default='pending',
            nullable=False,
        ),
        sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            'currency', sa.String(length=8), server_default='RUB', nullable=False
        ),
        sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'provider', 'provider_payment_id', name='uq_provider_payment'
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments', if_exists=True)
    sa.Enum(name='payment_status').drop(
        op.get_bind(),
        checkfirst=True,
    )
    # ### end Alembic commands ###
