"""create orders table

Revision ID: 3f7e969eb6de
Revises: 831d972d9ff7
Create Date: 2026-10-04 21:53:29.919467

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3f7e969eb6de'
down_revision: Union[str, Sequence[str], None] = '831d972d9ff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'orders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column(
            'status',
            sa.Enum('new', 'paid', 'cancelled', 'completed', name='order_status'),
            server_default='new',
            nullable=False,
        ),
        sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders', if_exists=True)
    sa.Enum(name='order_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
